### ISSUE TITLE
Allow BCHD GRPC with self-signed certificates

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/server#9]
https://memberapp.github.io/?b0df#thread?post=b0dfdc2b50

**Comment by JettScythe** [comment]
Is there anyway to make the regular RPC server work with self-signed certificates? If I run member normally I get `Client sent an HTTP request to an HTTPS server.`. If I specify the protocol to HTTPS I get `Error: Bitcoin JSON-RPC: Request Error: self signed certificate
`

Running against localhost I get `SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/snapshot/Cash/node_modules/bitcoind-rpc/lib/index.js:123:26)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Client sent an HTTP request to an HTTPS server.
` as well

**Comment by JettScythe** [comment]
Hey FreeTrade! Just popping back in here to say that while I still think this would be a good enhancement, I've been running my bchd gRPC stuff behind caddy so I personally am not concerned about this anymore. 

That being said, I'm still getting errors on the regular bitcoind-rpc side of things that makes this impossible to run on my own infra. 

Running with notls commented out in bchd.conf I get 
`Error: Bitcoin JSON-RPC: Request Error: self signed certificate
    at ClientRequest.<anonymous> (/home/jettscythe/server/node_modules/bitcoind-rpc/lib/index.js:113:15)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:467:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

Running with it uncommented I get: 
`SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/jettscythe/server/node_modules/bitcoind-rpc/lib/index.js:97:26)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Client sent an HTTP request to an HTTPS server.
`

**Comment by FreeTrade** [comment]
removing gRPC so closing
